"""fresh_neon_build

Revision ID: b469e3c6ea4e
Revises: 
Create Date: 2026-03-12 22:38:29.673934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b469e3c6ea4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FACULTY', name='role'), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('bookpublication',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher_details', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_month_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferencepublication',
    sa.Column('title_of_paper', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conference_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('held_on', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journalpublication',
    sa.Column('title_of_paper', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('journal_type', sa.Enum('INTERNATIONAL', 'NATIONAL', name='journaltype'), nullable=False),
    sa.Column('journal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_month_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journalpublication')
    op.drop_table('conferencepublication')
    op.drop_table('bookpublication')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
